name: crates
on: 
  push:
    branches: main
jobs:
  matrix-generator:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner.
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8 #install the python needed
      - id: set-matrix
        run: |
          SERVICES=$( python -c 'import crates.service as s; import json; print(json.dumps(s.ALL))' )
          echo "{\"services\":${SERVICES}}"
          echo "::set-output name=matrix::$( echo "{\"services\":${SERVICES}}" )"
  docker-build:
    needs: matrix-generator
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{fromJson(needs.matrix-generator.outputs.matrix)}}
    steps:
      - run: echo Building ${{ matrix.services }} Docker
      - 
        name: Checkout
        uses: actions/checkout@v2
      - 
        name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8 #install the python needed
      - 
        name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - 
        name: Build Dockerfile
        run: python -m crates.docker.builder ${{ matrix.services }} > Dockerfile.${{ matrix.services }}        
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          driver-opts: image=moby/buildkit:master
      - 
        name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y%m%d%H%M')"
      -
        name: Login to the GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}
      - 
        name: Build and push image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          file: ./Dockerfile.${{ matrix.services }}
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ github.workflow }}-${{ matrix.services }}:${{ steps.date.outputs.date }}
            ghcr.io/${{ github.repository_owner }}/${{ github.workflow }}-${{ matrix.services }}:latest
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}