name: build
on: push
jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner.
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8 #install the python needed
      - id: set-matrix
        run: echo "::set-output name=matrix::{\"include\":$( python -c 'import crates.service as s; import json; print(json.dumps(json.dumps(s.ALL)))' )}"
  job2:
    needs: job1
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        service: ${{fromJson(needs.job1.outputs.matrix)}}
    steps:
      - run: echo ${{ matrix }}
